---
- name: install solar and configurations
  hosts: ansiblehost
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: 
        update_cache: true
        cache_valid_time: 3600

  handlers:
    - name: restart solr
      service: 
        name: solr
        state: restarted

  tasks:
    - name: Install Java.
      apt: 
        name: openjdk-8-jdk 
        state: present
    
    - name: Download Solr.
      get_url:      
#        url: 'https://mirror.nbtelecom.com.br/apache/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz'
        url: "https://downloads.apache.org/lucene/solr/8.8.2/solr-8.8.2-src.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version}}.tgz"
        checksum: "{{ solr_checksum }}"        
        timeout: 100

    - name: Expand Solr.
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version}}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"        
    
#    - name: Permission
#      shell: |
#        chmod 777 /tmp/solr-8.8.2/solr/bin/install_solr_service.sh
        

    - name: Run Solr installation script.
      shell: |
        tar xzf /tmp/solr-8.8.2.tgz solr-8.8.2/solr/bin/install_solr_service.sh --strip-components=2

#        {{ download_dir }}/solr-{{ solr_version }}/solr/bin/install_solr_service.sh
#        {{ download_dir }}/solr-{{ solr_version }}.tgz
#        -i /opt
#        -d /var/solr
#        -u solr
#        -s solr
#        -p 8983
#        creates={{ solr_dir }}solr/bin/solr

    - name: Ensure solr is started and enabled at boot.
      service: 
        name: solr
        state: started
        enabled: yes




