---
  - name: Install apache and necessary configuration.
    hosts: all
    become: yes # when the become is defined here all tasks will be executed as a root user.

    tasks:
      - name: Install Apache.
        yum:
          name: 
            - httpd
            - httpd-devel
          state: present
          become: true #this can be used if only one of few tasks from the playbook required root user
      
      - name: Copy configurations file.
        copy:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          owner: root
          group: root
          mode: 0644
        with_items:
          - src: httpd.conf
            dest: /etc/httpd/conf/httpd.conf
          - src: httpd-vhosts.conf
            dest: /etc/httpd/conf/httpd-vhosts.conf

      - name: Make sure Apache is started now and at boot.
        service:
          name: httpd
          state: started
          enabled: yes